name: optica_app
description: Aplicación óptica optimizada
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.5
  
  # Internacionalización (versión compatible con Flutter SDK)
  intl: ^0.20.2

  cached_network_image: ^3.3.0
  
  # Iconos
  cupertino_icons: ^1.0.8
  
  # Navegación y estado
  provider: ^6.1.1

  # Selector de archivos
  file_picker: ^10.3.7

  # Detectar plataforma
  universal_io: ^2.2.2 
  
  # HTTP
  http: ^1.1.0
  
  # Storage local
  shared_preferences: ^2.2.2
  
  # Envío de correos
  mailer: ^6.6.0

  # Soporte para localizaciones (calendario, fechas)
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true